### ISSUE TITLE
mitra - search returns only results for people

### ISSUE THREAD

**Issue by technicat** [technicat/fedicat#920]
no posts or tags, so should remove those tabs

**Comment by silverpill** [comment]
It depends on the search query:

- `@` prefix or no prefix: search people
- `#` prefix: search tags
- `>` prefix: search posts
- URLs: search for a post or a person by ID

This may change in the future though, I think by default (no prefix) Mitra will search for everything. So I'd keep those tabs just in case :)

**Comment by technicat** [comment]
Thanks for the info! I just tried searching for @cat on wizard.casa (running mitra 2.18.0) and it doesn't return anything but #cat does return tags and >cat returns posts.

**Comment by silverpill** [comment]
> I just tried searching for @cat on wizard.casa (running mitra 2.18.0) and it doesn't return anything

Do you mean it returns many other accounts but not yours? Or nothing at all?

**Comment by technicat** [comment]
Never mind, @cat works now, I don't know what was happening before.

**Comment by technicat** [comment]
![IMG_6524](https://github.com/technicat/fedicat/assets/1530082/8700557e-f8f2-4bdd-8945-a2e94d4d9bf9)

**Comment by silverpill** [comment]
Perhaps server should return local accounts first. What do you think?
